---

- name: Create Application
  become: false
  expect:
    echo: yes
    command: npx @backstage/create-app@latest 
    timeout: 1800 # 30mins
    responses:
      (.*)Ok to proceed(.*): "y"
      (.*)Enter a name for the app(.*): "sir-legendary-backstage"
    creates: /home/ubuntu/sir-legendary-backstage
