---

- name: Create Application
  become: false
  expect:
    echo: yes
    command: npx @backstage/create-app@latest 
    timeout: 800
    responses:
      (.*)Ok to proceed(.*): "y"
      (.*)Enter a name for the app(.*): "legendary-backstage"
    creates: /home/ubuntu/legendary-backstage
