---

- name: Add custom app config
  become: false
  template:
    src: app-config-local.yml.j2
    dest: /home/ubuntu/sir-legendary-backstage/app-config.yaml

- name: Add custom Dockerfile
  become: false
  template:
    src: dockerfile.j2
    dest: /home/ubuntu/sir-legendary-backstage/packages/backend/Dockerfile

- name: Host build
  become: false
  shell: |
    yarn install --frozen-lockfile
    yarn tsc
    yarn build:backend
  args:
    chdir: "/home/ubuntu/sir-legendary-backstage"

- name: Add Docker Clear script
  become: false
  template:
    src: docker_clear.sh.j2
    dest: /home/ubuntu/docker_clear.sh
    mode: u+rwx,g=rwx,o=r

- name: Clear Docker images and running containers
  shell: |
    ./docker_clear.sh
  args:
    chdir: "/home/ubuntu/"
  ignore_errors: true

- name: Build Docker image
  shell: |
    docker image build . -f packages/backend/Dockerfile --tag backstage:1.0.0
  args:
    chdir: "/home/ubuntu/sir-legendary-backstage"