---

- name: Create Application
  become: false
  expect:
    echo: yes
    command: npx @backstage/create-app@latest 
    timeout: 800
    responses:
      (.*)Ok to proceed(.*): "y"
      (.*)Enter a name for the app(.*): "sir-legendary-backstage"
    creates: /home/ubuntu/sir-legendary-backstage

- name: Add custom app config
  become: false
  template:
    src: app-config-local.yml.j2
    dest: /home/ubuntu/sir-legendary-backstage/app-config.yaml

- name: Add custom Dockerfile
  become: false
  template:
    src: dockerfile.j2
    dest: /home/ubuntu/sir-legendary-backstage/packages/backend/Dockerfile

- name: Host build
  become: false
  shell: |
    yarn install --frozen-lockfile
    yarn tsc
    yarn build:backend
  args:
    chdir: "/home/ubuntu/sir-legendary-backstage"

- name: Clear Docker images and running containers
  shell: |
    ./docker_clear.sh
  args:
    chdir: "/home/ubuntu/"

- name: Build Docker image
  shell: |
    docker image build . -f packages/backend/Dockerfile --tag backstage
  args:
    chdir: "/home/ubuntu/sir-legendary-backstage"